name: foot-wrench
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyyaml
  - jupyterlab
  - ipykernel
  - cvxpy
  - pytest
  - pip:
      - mujoco==3.1.3
